# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EatripApp', '0005_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EatripApp.Driver'),
        ),
    ]
